<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateFyersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        if (!Schema::hasTable('fyers')) {
            Schema::create('fyers', function (Blueprint $table) {
                $table->bigIncrements('fpm_ws_id');
                $table->integer('fyer_groups_id')->comment('FK to fyer_groups table (fyer_grp_id). Was save_name_id before.');

                //$table->integer('present_floorplans_id')->nullable()->comment('FK Floorplans table where machine is currently located');
                $table->integer('floorplan_machines_id')->comment('FK to floorplan_machines table (fpm_id). Was fpm_id before.');
                $table->integer('report_id')->comment('Sequential number for the FYER report. Was ID# before.');
                $table->integer('buildings_id')->nullable()->comment('Foreign key to the buildings table.');
                $table->string('present_room_name', 40)->nullable()->comment('Was present_room_number in old table. Current room number or name');

                $table->string('present_serial_number', 25)->nullable()->comment('Current serial_number. Was SerialNum.');
                $table->string('proposed_serial_number', 25)->nullable()->comment('Proposed serial_number. Was NewSerialNum.');
                $table->text('features_list')->nullable()->comment('Features of this machine.');
                $table->integer('speed')->nullable();
                $table->integer('present_black_volume')->nullable()->comment('Was Annual Volume before.');
                $table->integer('proposed_black_volume')->nullable()->comment('Was PropVol before');
                $table->integer('present_color_volume')->nullable()->comment('Was Color_Vol before.');
                $table->integer('proposed_color_volume')->nullable()->comment('Was ProjColorVol before.');

                $table->decimal('present_cpc_black', 7, 6)->nullable()->comment('Current cost per copy black. Was AdjCostCopy before.');
                $table->decimal('proposed_cpc_black', 7, 6)->nullable()->comment('Proposed cost per copy black. Was PropCost before.');
                $table->decimal('present_cpc_color', 7, 6)->nullable()->comment('Current cost per copy color. Was Color_CPC before.');
                $table->decimal('proposed_cpc_color', 7, 6)->nullable()->comment('Proposed cost per copy color. Was NewColorCPC before.');

                $table->decimal('present_cpc_black_vendor', 7, 6)->nullable();
                $table->decimal('present_cpc_color_vendor', 7, 6)->nullable();
                $table->decimal('proposed_cpc_black_vendor', 7, 6)->nullable();
                $table->decimal('proposed_cpc_color_vendor', 7, 6)->nullable();

                $table->string('present_vendor_mach_id', 50)->nullable()->comment('The id that the vendor generates for a specific machine. Was VendorID before.');
                $table->string('proposed_vendor_mach_id', 50)->nullable()->comment('Proposed vendor machine id number generated by vendor. Was NewVendorID before.');
                $table->integer('present_type_id')->nullable()->comment('Present machine type. Kept for now, but may not need');
                $table->integer('proposed_type_id')->nullable()->comment('Foreign key to the machine_types table, col mach_type_id. Was GroupTag before.');
                $table->integer('present_model_id')->nullable();
                $table->integer('proposed_model_id')->nullable();

                $table->integer('bid_meter')->nullable()->comment('Budgeted black volume');
                $table->dateTime('intro_date')->nullable()->comment('Date machine was introduced. Was Intro before.');
                $table->dateTime('proposed_intro_date')->nullable()->comment('Proposed date to introduce the machine. Was prop_intro before.');
                $table->integer('life')->nullable()->comment('life of the machine.');
                $table->integer('proposed_life')->nullable()->comment('Was prop_life before.');
                $table->string('move_to', 25)->nullable()->comment('Machine move to location.'); //Max length is currently 29
                $table->string('move_from', 25)->nullable()->comment('Machine move from location.'); //Max length is currently 8
                $table->string('first_year_equip', 255)->nullable()->comment('Was 1stYearEquipment.');//Max length is currently 252
                $table->string('second_year_equip', 255)->nullable()->comment('Was 2ndYear.');//Max length is currently 15
                $table->string('third_year_equip', 255)->nullable()->comment('Was 3rdYear.');//Max length is currently 15
                $table->string('fourth_year_equip', 255)->nullable()->comment('Was 4thYear.');//Max length is currently 15
                $table->string('fifth_year_equip', 255)->nullable()->comment('Was 5thYear.');//Max length is currently 15

                $table->integer('vendor_id')->nullable()->comment('Foreign key to the organizations table.');

                $table->integer('forced_upgrades')->nullable();
                $table->decimal('service_supplies', 11, 6)->nullable()->comment('Was S&&S before.');
                $table->dateTime('install_date')->nullable()->comment('Was Install before.');
                $table->char('lease_own', 1)->nullable()->comment('Type of Possession. L=Leased, O=Owned, R=Rental, B=Loaner(Borrowed)');

                $table->string('ip_address', 30)->nullable()->comment('IP address from FM Audit, I believe. Was IP_Address before.');
                $table->string('mac_address', 30)->nullable()->comment('Mac address from FM Audit.');
                $table->string('special_notes', 255)->nullable()->comment('Was Special_Notes before.');//Max length is currently 15

                $table->integer('commencement_black_meter')->nullable();
                $table->integer('commencement_color_meter')->nullable();
                $table->integer('departments_id')->nullable()->comment('FK to the departments table. Was dept_id before.');

                $table->timestamp('created_date')->useCurrent()->comment('Date and time the fyer was created. Was Created before.');
                $table->integer('created_by')->comment('Was Created By before.');
                $table->timestamp('modified_date')->useCurrent()->comment('Was Modified before.');
                $table->integer('modified_by')->comment('Was Modified By before.');
                $table->dateTime('deleted_at')->nullable();
            });
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('fyers');
    }
}
